FROM node:20-alpine AS base

RUN apk update && apk add git

FROM base AS web-builder

RUN mkdir -p /app
WORKDIR /app

COPY . .

RUN yarn install
RUN yarn build-web

FROM base AS server

RUN mkdir -p /app
WORKDIR /app

COPY ./auth-server/* ./

RUN yarn install

COPY --from=web-builder /app/web-build /app/public/

EXPOSE 3000

CMD ["yarn", "start"]
